model={
	appName:"contrarian",
	title:"contrarian",

	bounds:{},
	paper:{},

	interests:[
		"Morgan",
		"Fiona",
		"Space",
		"Dinosaurs",
		"Evolution",
		"Javascript",
		"Impact",
		"Anarchism",
		"Character",
		"The Society of the Mind",
		"Secrets",
		"Neuroscience",
		"Markov Chains",
		"Creation",
		"Luke",
		"Genetics",
		"Language Analytics",
		"Good",
		"ROI",
		"Zen",
		"Love",
		"Courage",
		"Wonder",
		"Awe",
		"Nature",
		"Art",
		"Data Vis"
	],

	images:[
		"./images/1.JPG",
		"./images/2.JPG",
		"./images/3.JPG",
		"./images/4.JPG",
		"./images/5.JPG",
		"./images/6.JPG",
		"./images/7.JPG",
		"./images/8.JPG"
	],

	icons:[
		"./images/github-64.png",
		"./images/pinterest-64.png",
		"./images/twitter-64.png",
		"./images/facebook-64.png",
		"./images/google-64.png",
		"./images/instagram-64.png",
		"./images/codecademy-64.png",
		"./images/codeschool-64.png",
		"./images/dropbox-64.png",
		"./images/drupal-64.png",
		"./images/deviantart-64.png",
		"./images/email-64.png",
		"./images/foursquare-64.png",
		"./images/gmail-64.png",
		"./images/googleplus-64.png",
		"./images/khanacademy-64.png",
		"./images/kickstarter-64.png",
		"./images/lastfm-64.png",
		"./images/linkedin-64.png",
		"./images/reddit-64.png",
		"./images/rss-64.png",
		"./images/skype-64.png",
		"./images/spotify-64.png",
		"./images/soundcloud-64.png",
		"./images/stackoverflow-64.png",
		"./images/steam-64.png",
		"./images/spotify-64.png",
		"./images/tumblr-64.png",
		"./images/vine-64.png",
		"./images/whatsapp-64.png",
		"./images/wikipedia-64.png",
		"./images/youtube-64.png",
		"./images/yelp-64.png"
	]

};
